#os arquivos de anotacao do:
#mil genomas
[[annotation]]
file="ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz"
fields = ["EAS_AF", "EUR_AF", "AFR_AF", "SAS_AF", "AMR_AF", "AF"]
ops=["max","max","max","max", "max","max"]
names=["1kgp_af_eas", "1kgp_af_eur", "1kgp_af_afr", "1kgp_af_sas", "1kgp_af_amr", "af_1kgp_all"]
#dbsnp
[[annotation]]
file="dbsnp.vcf.gz"
fields = ["ID"]
ops=["concat"]
names=["dbsnp_rs"]

